export const DATA_COLLECTION_TAG_NAME_MAX_LENGTH = 40;
export const DATA_COLLECTION_BATCH_NAME_MAX_LENGTH = 250;
export const SAMPLE_NAME_MAX_LENGTH = 250;
export const SEQUENCE_COLLECTION_NAME_MAX_LENGTH = 250;
