export const DATA_COLLECTION_TAG_NAME_MAX_LENGTH = 40;
export const DATA_COLLECTION_BATCH_NAME_MAX_LENGTH = 250;
export const SEQUENCE_SET_NAME_MAX_LENGTH = 250;
export const RUN_DATA_COLLECTION_NAME_MAX_LENGTH = 250;
