import { CfnOutput, Stack } from 'aws-cdk-lib';
import { NagSuppressions } from 'cdk-nag';
import { Construct } from 'constructs';
import { DataProvisioningNestedStack } from './data-provisioning-nested-stack';
import { EasyGenomicsNestedStack } from './easy-genomics-nested-stack';
import { ApiGatewayConstruct } from '../constructs/api-gateway-construct';
import {
  DataProvisioningNestedStackProps,
  EasyGenomicsApiStackProps,
  EasyGenomicsNestedStackProps,
} from '../types/back-end-stack';

/**
 * Dedicated top-level stack that owns the Easy Genomics REST API and all of its
 * route registrations. It was split out of `BackEndStack` because the Easy
 * Genomics route set alone was enough to push the shared back-end stack past
 * the 500-resource CloudFormation limit (see `split_easy_api_*.plan.md`).
 *
 * Contained nested stacks:
 *  - `EasyGenomicsNestedStack`: domain resources (DynamoDB, SNS, SQS, SES, Lambdas).
 *  - `DataProvisioningNestedStack`: co-located here rather than in `BackEndStack`
 *    so it can keep using the in-process `Map<string, Table>` from the easy-genomics
 *    nested stack without creating a large number of CloudFormation exports.
 *
 * IMPORTANT - migration from the pre-split stack layout:
 *  - For **fresh** deploys (brand-new environments with no existing tables),
 *    the refactor is safe: CDK creates the new stack and its tables from
 *    scratch.
 *  - For **existing** deploys in ANY environment (dev, demo, pre-prod, prod),
 *    the eight easy-genomics DynamoDB tables carry real data AND are pinned
 *    to `RemovalPolicy.RETAIN` with deletion protection (see
 *    `dynamodb-construct.ts`). A naive `cdk deploy --all` will fail because
 *    the retained tables still hold the fixed physical names that the new
 *    stack wants to create. The supported migration path is documented in
 *    `docs/EASY_GENOMICS_PROD_MIGRATION.md` (retain → detach → `cdk import`).
 *    That runbook is intentionally environment-agnostic so the prod rollout
 *    is a rehearsed repeat of non-prod rollouts.
 */
export class EasyGenomicsApiStack extends Stack {
  readonly props: EasyGenomicsApiStackProps;
  readonly apiGateway: ApiGatewayConstruct;
  readonly easyGenomicsNestedStack: EasyGenomicsNestedStack;

  constructor(scope: Construct, id: string, props: EasyGenomicsApiStackProps) {
    // NOTE: Do not pass `env` to super here. `BackEndStack` uses the CDK
    // environment-agnostic default; passing a concrete env here would make the
    // two sibling top-level stacks deploy to "different" environments from
    // CDK's perspective and break cross-stack references to Cognito/VPC.
    super(scope, id);
    this.props = props;

    // Dedicated API Gateway for the Easy Genomics domain. Keeping the API at
    // this stack level means all `AWS::ApiGateway::{Method,Resource}` and
    // `AWS::Lambda::Permission` resources generated by `LambdaConstruct` land
    // in this stack template (not in `BackEndStack`).
    this.apiGateway = new ApiGatewayConstruct(this, `${this.props.namePrefix}-easy-genomics-apigw`, {
      description: 'Easy Genomics API Gateway',
    });

    const easyGenomicsNestedStackProps: EasyGenomicsNestedStackProps = {
      ...this.props,
      constructNamespace: `${this.props.namePrefix}-easy-genomics`,
      restApi: this.apiGateway.restApi,
    };
    this.easyGenomicsNestedStack = new EasyGenomicsNestedStack(
      this,
      `${this.props.envName}-easy-genomics-nested-stack`,
      easyGenomicsNestedStackProps,
    );

    // Data provisioning is co-located (parented by this stack) so it can reach
    // into `easyGenomicsNestedStack.dynamoDBTables` directly. Passing a
    // `Map<string, Table>` across stack boundaries would force a large number
    // of CloudFormation exports and make future refactors painful.
    const dataProvisioningNestedStackProps: DataProvisioningNestedStackProps = {
      ...this.props,
      constructNamespace: `${this.props.namePrefix}-data-provisioning`,
      userPool: this.props.userPool,
      userPoolSystemAdminGroupName: this.props.userPoolSystemAdminGroupName,
      dynamoDBTables: this.easyGenomicsNestedStack.dynamoDBTables,
    };
    new DataProvisioningNestedStack(this, 'data-provisioning-nested-stack', dataProvisioningNestedStackProps);

    // Emit the Easy Genomics API URL. Kept as a distinct output so the
    // front-end `EASY_GENOMICS_API_URL` env var can resolve to this invoke URL
    // in non-prod, and a custom domain alias in prod (when configured).
    new CfnOutput(this, 'EasyGenomicsApiUrl', {
      key: 'EasyGenomicsApiUrl',
      value: this.apiGateway.restApi.url,
    });

    this.applyNagSuppressions();
  }

  /**
   * Nag suppressions relocated from `BackEndStack` so their hardcoded
   * construct paths resolve against this stack's tree after the split.
   * These paths are stack-relative: they start with this stack's name.
   */
  private applyNagSuppressions = () => {
    const stackPath = `/${this.stackName}`;
    const apigwId = `${this.props.namePrefix}-easy-genomics-apigw`;
    const nestedId = `${this.props.envName}-easy-genomics-nested-stack`;
    const easyGenomicsId = `${this.props.namePrefix}-easy-genomics`;

    // User signup and password recovery endpoints do not require an authorizer.
    const publicAuthEndpointPaths = [
      `${stackPath}/${apigwId}/${apigwId}/Default/easy-genomics/user/confirm-user-invitation-request/POST/Resource`,
      `${stackPath}/${apigwId}/${apigwId}/Default/easy-genomics/user/create-user-forgot-password-request/POST/Resource`,
      `${stackPath}/${apigwId}/${apigwId}/Default/easy-genomics/user/confirm-user-forgot-password-request/POST/Resource`,
    ];

    NagSuppressions.addResourceSuppressionsByPath(
      this,
      publicAuthEndpointPaths,
      [
        {
          id: 'AwsSolutions-APIG4',
          reason: 'These are used for user signup or password recovery and do not require an authorizer',
        },
      ],
      true,
    );

    NagSuppressions.addResourceSuppressionsByPath(
      this,
      publicAuthEndpointPaths,
      [
        {
          id: 'AwsSolutions-COG4',
          reason: 'These are used for user signup or password recovery and do not require an authorizer',
        },
      ],
      true,
    );

    // Lambda execution roles that require broader S3 access (signed URLs,
    // bucket listing, multi-object downloads, etc.).
    NagSuppressions.addResourceSuppressionsByPath(
      this,
      [
        `${stackPath}/${nestedId}/${easyGenomicsId}/${easyGenomicsId}-request-file-download-url/ServiceRole/DefaultPolicy/Resource`,
        `${stackPath}/${nestedId}/${easyGenomicsId}/${easyGenomicsId}-request-list-bucket-objects/ServiceRole/DefaultPolicy/Resource`,
        `${stackPath}/${nestedId}/${easyGenomicsId}/${easyGenomicsId}-request-search-bucket-objects/ServiceRole/DefaultPolicy/Resource`,
        `${stackPath}/${nestedId}/${easyGenomicsId}/${easyGenomicsId}-request-folder-download-job/ServiceRole/DefaultPolicy/Resource`,
        `${stackPath}/${nestedId}/${easyGenomicsId}/${easyGenomicsId}-request-folder-download-job-status/ServiceRole/DefaultPolicy/Resource`,
        `${stackPath}/${nestedId}/${easyGenomicsId}/${easyGenomicsId}-process-folder-download-job/ServiceRole/DefaultPolicy/Resource`,
        `${stackPath}/${nestedId}/${easyGenomicsId}/${easyGenomicsId}-update-laboratory/ServiceRole/DefaultPolicy/Resource`,
        `${stackPath}/${nestedId}/${easyGenomicsId}/${easyGenomicsId}-list-buckets/ServiceRole/DefaultPolicy/Resource`,
        `${stackPath}/${nestedId}/${easyGenomicsId}/${easyGenomicsId}-create-file-upload-request/ServiceRole/DefaultPolicy/Resource`,
        `${stackPath}/${nestedId}/${easyGenomicsId}/${easyGenomicsId}-create-file-upload-sample-sheet/ServiceRole/DefaultPolicy/Resource`,
      ],
      [
        {
          id: 'AwsSolutions-IAM5',
          reason: 'Require access to S3',
        },
      ],
      true,
    );

    // Lab Runs processor needs access to read any omics run to fetch status.
    NagSuppressions.addResourceSuppressionsByPath(
      this,
      [
        `${stackPath}/${nestedId}/${easyGenomicsId}/${easyGenomicsId}-process-update-laboratory-run/ServiceRole/DefaultPolicy/Resource`,
      ],
      [
        {
          id: 'AwsSolutions-IAM5',
          reason: 'Needs access to all omics runs to fetch their current status',
          appliesTo: [`Resource::arn:aws:omics:${this.props.env.region!}:${this.props.env.account!}:run/*`],
        },
      ],
      true,
    );
  };
}
