import { join } from 'path';
import { getApiGatewayInfo } from '@easy-genomics/shared-lib/lib/src/app/utils/api-gateway-utils';
import {
  getCognitoClientUrls,
  getCognitoDomainInfo,
  getCognitoIdpInfo,
} from '@easy-genomics/shared-lib/lib/src/app/utils/cognito-idp-utils';
import { ApiGatewayInfo } from '@easy-genomics/shared-lib/src/app/types/api-gateway-info';
import { CognitoIdpInfo } from '@easy-genomics/shared-lib/src/app/types/cognito-idp-info';
import { ConfigurationSettings } from '@easy-genomics/shared-lib/src/app/types/configuration';
import { loadConfigurations } from '@easy-genomics/shared-lib/lib/src/app/utils/configuration';
import * as fs from 'fs';

/**
 * This script is required to simplify the easy-genomics.yaml configuration and deployment workflow for customers and
 * for the Easy Genomics development team to easily work on various parts of the system in parallel.
 *
 * This script reads the {easy-genomics root dir}/config/easy-genomics.yaml file for the configured shared settings to
 * then asynchronously queries the relevant AWS services for the existing:
 *  - API Gateway URL
 *  - Cognito IDP User Pool ID
 *  - Cognito IDP User Pool Client ID
 *
 * This information is then saved to the {easy-genomics root dir}/config/.env.nuxt file for Nuxt's nuxt.config.ts
 * to use for the static web content generation.
 *
 * Once the project configuration is able to allow top-level asynchronous calls from either the Front-End main.ts
 * entry point or the nuxt.config.ts entry point, this intermediate script can be deprecated.
 *
 * @param awsRegion
 * @param envName
 * @param envType
 * @param easyGenomicsApiUrl Optional override for the easy-genomics API URL (no trailing slash).
 */
export async function exportNuxtConfigurationSettings(
  awsRegion: string,
  envName: string,
  envType: string,
  easyGenomicsApiUrl?: string,
) {
  const namePrefix: string = `${envType}-${envName}`;
  const apiGatewayRestApiName: string = `${namePrefix}-easy-genomics-apigw`;
  const cognitoUserPoolName: string = `${namePrefix}-easy-genomics-auth-user-pool`;
  const cognitoUserPoolClientName: string = `${namePrefix}-easy-genomics-auth-user-pool-client`;

  // Ensure the AWS Region for the SDK calls to correctly query the correct region.
  process.env.AWS_REGION = awsRegion;
  const apiGatewayInfo: ApiGatewayInfo = await getApiGatewayInfo(apiGatewayRestApiName, awsRegion);
  const cognitoIdpInfo: CognitoIdpInfo = await getCognitoIdpInfo(cognitoUserPoolName, cognitoUserPoolClientName);
  const cognitoDomain = await getCognitoDomainInfo(cognitoIdpInfo.UserPoolId || '');
  const clientUrls = await getCognitoClientUrls(cognitoIdpInfo.UserPoolId || '', cognitoIdpInfo.UserPoolClientId || '');
  const { callbackUrls, logoutUrls } = clientUrls;

  console.log('Retrieve and export Nuxt Configuration Settings...');
  console.log(`  AWS_REGION=${awsRegion}`);
  console.log(`  ENV_NAME=${envName}`);
  console.log(`  ENV_TYPE=${envType}`);
  console.log(`  AWS_API_GATEWAY_URL=${apiGatewayInfo.RestApiUrl}`);
  if (easyGenomicsApiUrl) {
    console.log(`  AWS_EASY_GENOMICS_API_URL=${easyGenomicsApiUrl}`);
  }
  console.log(`  AWS_COGNITO_USER_POOL_ID=${cognitoIdpInfo.UserPoolId}`);
  console.log(`  AWS_COGNITO_USER_POOL_CLIENT_ID=${cognitoIdpInfo.UserPoolClientId}`);
  console.log(`  AWS_COGNITO_DOMAIN=${cognitoDomain}`);

  const normalizedEasyGenomicsApiUrl = easyGenomicsApiUrl?.replace(/\/+$/, '');
  const nuxtConfigurationSettings: string =
    '###\n' +
    '# This configuration file is generated by the Front-End nuxt-load-configuration-settings.ts script.\n' +
    '###\n' +
    `AWS_REGION=${awsRegion}\n` +
    `ENV_NAME=${envName}\n` +
    `ENV_TYPE=${envType}\n` +
    `AWS_API_GATEWAY_URL=${apiGatewayInfo.RestApiUrl}\n` +
    `AWS_EASY_GENOMICS_API_URL=${normalizedEasyGenomicsApiUrl ?? ''}\n` +
    `AWS_COGNITO_USER_POOL_ID=${cognitoIdpInfo.UserPoolId}\n` +
    `AWS_COGNITO_USER_POOL_CLIENT_ID=${cognitoIdpInfo.UserPoolClientId}\n` +
    `AWS_COGNITO_DOMAIN=${cognitoDomain ?? ''}\n` +
    `COGNITO_CALLBACK_URLS=${callbackUrls}\n` +
    `COGNITO_LOGOUT_URLS=${logoutUrls}\n`;

  fs.writeFileSync(join(__dirname, '../../config/.env.nuxt'), nuxtConfigurationSettings, {
    encoding: 'utf8',
    flush: true,
  });
}

function isCredentialsError(error: unknown): boolean {
  const name = error && typeof error === 'object' && 'name' in error ? (error as { name?: string }).name : '';
  const code = error && typeof error === 'object' && 'code' in error ? (error as { code?: string }).code : '';
  return name === 'CredentialsProviderError' || code === 'CredentialsProviderError';
}

// eslint-disable-next-line no-void
void (async () => {
  try {
    if (process.env.CI_CD === 'true') {
      const awsRegion = process.env.AWS_REGION;
      const envName = process.env.ENV_NAME;
      const envType = process.env.ENV_TYPE;
      const easyGenomicsApiUrl = process.env.AWS_EASY_GENOMICS_API_URL;
      if (!awsRegion || !envName || !envType) {
        throw new Error('Missing required CI/CD env vars: AWS_REGION, ENV_NAME, ENV_TYPE.');
      }

      await exportNuxtConfigurationSettings(awsRegion, envName, envType, easyGenomicsApiUrl);
    } else {
      // @ts-ignore
      const configurations: { [p: string]: ConfigurationSettings }[] = loadConfigurations(
        // `__dirname` here is `packages/front-end`. The repo-level config lives at `config/easy-genomics.yaml`.
        join(__dirname, '../../config/easy-genomics.yaml'),
      );
      if (configurations.length === 0) {
        throw new Error('Easy Genomics Configuration missing / invalid, please update: easy-genomics.yaml');
      } else if (configurations.length > 1) {
        throw new Error('Too many Easy Genomics Configurations found, please update: easy-genomics.yaml');
      } else {
        const configuration: { [p: string]: ConfigurationSettings } | undefined = configurations.shift();

        if (configuration) {
          const envName: string | undefined = Object.keys(configuration).shift();
          const configSettings: ConfigurationSettings | undefined = Object.values(configuration).shift();

          if (!envName || !configSettings) {
            throw new Error(
              'Easy Genomics Configuration missing / invalid, please check the easy-genomics.yaml configuration',
            );
          }

          const envType: string = configSettings['env-type']; // dev | pre-prod | prod
          const awsRegion: string = configSettings['aws-region'];
          const easyGenomicsApiUrl: string | undefined = configSettings['aws-easy-genomics-api-url'] ?? undefined;

          await exportNuxtConfigurationSettings(awsRegion, envName, envType, easyGenomicsApiUrl);
        }
      }
    }
  } catch (error) {
    if (isCredentialsError(error)) {
      console.error(
        '\nAWS credentials could not be loaded. This script needs credentials to call API Gateway and Cognito.',
      );
      console.error('Configure credentials using one of these methods:\n');
      console.error('  1. Run:  aws configure');
      console.error('     Then set AWS Access Key ID, Secret Access Key, and Default region (e.g. us-west-2).\n');
      console.error('  2. If using AWS SSO, run:  aws sso login');
      console.error('     Then ensure AWS_PROFILE is set or use:  aws sso login --profile YOUR_PROFILE\n');
      console.error('  3. Set environment variables: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION');
      console.error('     (and AWS_SESSION_TOKEN if using temporary credentials).\n');
      process.exit(1);
    }
    throw error;
  }
})();
